### ISSUE TITLE
Screen not working after retropie update to 4.5.1 

### ISSUE THREAD

**Issue by mosse-r** [withgallantry/RetropieFE#5]
This was after an upgrade from the retropie setup menu. I don't see any /dev/fb1 device which I would expect. 

Possibly an issue with a driver/overlay?

**Comment by Superpuissant** [comment]
Hi, same issue reported in the issue #3 Configure Input/Leave game. withgallantry advised he will look when he has time... I can't wait to have a usuable device one year after having order it! :-)

**Comment by withgallantry** [comment]
@mosse-r It is an issue with the overlay being replaced due to an upgrade, amongst other things. 
Starting upgrade replaces key files that have been modified to work with the Pocket FE Hardware. There are steps to replace the files after updating but it is quite a complicated process. Would you be interested in me documenting this?

**Comment by Superpuissant** [comment]
Hi, yes, having the steps document would definitely be an improvement. Thank you for proposing it.

**Comment by mosse-r** [comment]
Thanks @withgallantry that would be great.

**Comment by withgallantry** [comment]
@mosse-r Fix can be found here:
https://github.com/withgallantry/RetropieFE/releases/tag/PiUpdate

Please open another issue if there is a problem with it :)
